### ISSUE TITLE
Add "hash" column to hmwk_completion_tracking board used in workspace template

### ISSUE THREAD

**Issue by lrt98802** [hmwkhmwk/hmwk#13]

**Comment by ceciliachung** [comment]
Done. I called it uniqueLink and added a description of what it is, so teachers don't have to wonder what "hash" means. Also realized we can do a lot more with the columns (adding a description, locking the edit permissions, etc.). I added a lock so teachers can't edit the uniqueLink (our server autogenerates and populates it), but will need Kay to test it because I'm not sure if that's what it does. I think potentially we can also hide this column from the teacher, but not sure what would be less confusing for them (another Kay question).
<img width="1258" alt="Screen Shot 2020-11-08 at 7 39 33 PM" src="https://user-images.githubusercontent.com/42010065/98488989-228ae280-21fa-11eb-9285-91c35b53c221.png">
